# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AnyUrl, BaseModel, Extra, Field, conint, constr

from . import v2 as v2_1
from .partner import v2


class SearchFilter(BaseModel):
    __root__: str = Field(..., description='Filter a collection by a string search')


class ObjectMeta(BaseModel):
    self: AnyUrl = Field(
        ...,
        description='Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the service location, API version, and other particulars necessary to locate the resource at a point in time',
        example='https://api.confluent.cloud/v2/kafka-clusters/lkc-f3a90de',
    )
    resource_name: Optional[AnyUrl] = Field(
        None,
        description='Resource Name is a Uniform Resource Identifier (URI) that is globally unique across space and time. It is represented as a Confluent Resource Name',
        example='crn://confluent.cloud/kafka=lkc-f3a90de',
    )
    created_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.',
        example='2006-01-02T15:04:05-07:00',
    )
    updated_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was last updated. It is represented in RFC3339 format and is in UTC.',
        example='2006-01-02T15:04:05-07:00',
    )
    deleted_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was (or will be) deleted. It is represented in RFC3339 format and is in UTC.',
        example='2006-01-02T15:04:05-07:00',
    )


class ListMeta(BaseModel):
    first: Optional[AnyUrl] = Field(
        None,
        description='A link to the first page of results. If a response does not contain a first link, then direct navigation to the first page is not supported.',
        example='https://api.confluent.cloud/v2/resourcekinds',
    )
    last: Optional[AnyUrl] = Field(
        None,
        description='A link to the last page of results. If a response does not contain a last link, then direct navigation to the last page is not supported.',
        example='https://api.confluent.cloud/v2/resourcekinds?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[AnyUrl] = Field(
        None,
        description='A link to the previous page of results. If a response does not contain a prev link, then either there is no previous data or backwards traversal through the result set is not supported.',
        example='https://api.confluent.cloud/v2/resourcekinds?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[AnyUrl] = Field(
        None,
        description='A link to the next page of results. If a response does not contain a next link, then there is no more data available.',
        example='https://api.confluent.cloud/v2/resourcekinds?page_token=UvmDWOB1iwfAIBPj6EYb',
    )
    total_size: Optional[conint(ge=0)] = Field(
        None,
        description='Number of records in the full result set. This response may be paginated and have a smaller number of records.',
        example=123,
    )


class ObjectReference(BaseModel):
    id: constr(min_length=1, max_length=255) = Field(
        ..., description='ID of the referred resource'
    )
    environment: Optional[constr(min_length=1, max_length=255)] = Field(
        None, description='Environment of the referred resource, if env-scoped'
    )
    related: AnyUrl = Field(
        ..., description='API URL for accessing or modifying the referred object'
    )
    resource_name: AnyUrl = Field(
        ..., description='CRN reference to the referred resource'
    )
    api_version: Optional[constr(min_length=1)] = Field(
        None, description='API group and version of the referred resource'
    )
    kind: Optional[constr(min_length=1)] = Field(
        None, description='Kind of the referred resource'
    )


class TypedGlobalObjectReference(BaseModel):
    id: constr(min_length=1, max_length=255) = Field(
        ..., description='ID of the referred resource'
    )
    related: AnyUrl = Field(
        ..., description='API URL for accessing or modifying the referred object'
    )
    resource_name: AnyUrl = Field(
        ..., description='CRN reference to the referred resource'
    )
    api_version: Optional[constr(min_length=1)] = Field(
        None, description='API group and version of the referred resource'
    )
    kind: Optional[constr(min_length=1)] = Field(
        None, description='Kind of the referred resource'
    )


class TypedEnvScopedObjectReference(BaseModel):
    id: constr(min_length=1, max_length=255) = Field(
        ..., description='ID of the referred resource'
    )
    environment: Optional[constr(min_length=1, max_length=255)] = Field(
        None, description='Environment of the referred resource, if env-scoped'
    )
    related: AnyUrl = Field(
        ..., description='API URL for accessing or modifying the referred object'
    )
    resource_name: AnyUrl = Field(
        ..., description='CRN reference to the referred resource'
    )
    api_version: Optional[constr(min_length=1)] = Field(
        None, description='API group and version of the referred resource'
    )
    kind: Optional[constr(min_length=1)] = Field(
        None, description='Kind of the referred resource'
    )


class Source(BaseModel):
    pointer: Optional[str] = Field(
        None,
        description='A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec object, or "/spec/title" for a specific field].',
    )
    parameter: Optional[str] = Field(
        None, description='A string indicating which query parameter caused the error.'
    )


class Error(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[constr(max_length=255)] = Field(
        None,
        description='A unique identifier for this particular occurrence of the problem.',
    )
    status: Optional[str] = Field(
        None,
        description='The HTTP status code applicable to this problem, expressed as a string value.',
    )
    code: Optional[str] = Field(
        None,
        description='An application-specific error code, expressed as a string value.',
    )
    title: Optional[str] = Field(
        None,
        description='A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence of the problem, except for purposes of localization.',
    )
    detail: Optional[str] = Field(
        None,
        description='A human-readable explanation specific to this occurrence of the problem.',
    )
    source: Optional[Source] = Field(
        None,
        description='If this error was caused by a particular part of the API request, the source will point to the query string parameter or request body property that caused it.',
    )
    error_code: Optional[int] = None
    message: Optional[str] = None


class MultipleSearchFilter(BaseModel):
    __root__: List[str] = Field(
        ..., description='Filter a collection by a string search for one or more values'
    )


class GlobalObjectReference(BaseModel):
    id: constr(min_length=1, max_length=255) = Field(
        ..., description='ID of the referred resource'
    )
    related: AnyUrl = Field(
        ..., description='API URL for accessing or modifying the referred object'
    )
    resource_name: AnyUrl = Field(
        ..., description='CRN reference to the referred resource'
    )


class EnvScopedObjectReference(BaseModel):
    id: constr(min_length=1, max_length=255) = Field(
        ..., description='ID of the referred resource'
    )
    environment: Optional[constr(min_length=1, max_length=255)] = Field(
        None, description='Environment of the referred resource, if env-scoped'
    )
    related: AnyUrl = Field(
        ..., description='API URL for accessing or modifying the referred object'
    )
    resource_name: AnyUrl = Field(
        ..., description='CRN reference to the referred resource'
    )


class AclOperation(BaseModel):
    __root__: str


class AclPatternType(BaseModel):
    __root__: str


class AclPermission(BaseModel):
    __root__: str


class AclResourceType(Enum):
    UNKNOWN = 'UNKNOWN'
    ANY = 'ANY'
    TOPIC = 'TOPIC'
    GROUP = 'GROUP'
    CLUSTER = 'CLUSTER'
    TRANSACTIONAL_ID = 'TRANSACTIONAL_ID'
    DELEGATION_TOKEN = 'DELEGATION_TOKEN'


class Datum(BaseModel):
    name: str
    value: Optional[str] = None
    operation: Optional[str] = None


class AlterConfigBatchRequestData(BaseModel):
    data: List[Datum]
    validate_only: Optional[bool] = None


class AnyValue(BaseModel):
    __root__: Optional[Any] = None


class AuthorizedOperations(BaseModel):
    __root__: List[str]


class ClusterConfigType(BaseModel):
    __root__: str


class CreateAclRequestData(BaseModel):
    resource_type: AclResourceType
    resource_name: str
    pattern_type: AclPatternType
    principal: str
    host: str
    operation: AclOperation
    permission: AclPermission


class CreateAclRequestDataList(BaseModel):
    data: List[CreateAclRequestData]


class Config(BaseModel):
    name: str
    value: Optional[str] = None


class CreateTopicRequestData(BaseModel):
    topic_name: str
    partitions_count: Optional[int] = None
    replication_factor: Optional[int] = None
    configs: Optional[List[Config]] = None
    validate_only: Optional[bool] = None


class ConfigSource(BaseModel):
    __root__: str


class ConfigSynonymData(BaseModel):
    name: str
    value: Optional[str] = None
    source: ConfigSource


class ConsumerGroupState(BaseModel):
    __root__: str


class ConsumerGroupType(BaseModel):
    __root__: str


class ProduceResponseData(BaseModel):
    size: int
    type: str


class ProduceRequestData(BaseModel):
    type: Optional[str] = None
    data: Optional[AnyValue] = None


class ProduceRequestHeader(BaseModel):
    name: str
    value: Optional[str] = None


class Relationship(BaseModel):
    related: str


class ResourceCollectionMetadata(BaseModel):
    self: str
    next: Optional[str] = None


class ResourceMetadata(BaseModel):
    self: str
    resource_name: Optional[str] = None


class UpdateConfigRequestData(BaseModel):
    value: Optional[str] = None


class UpdatePartitionCountRequestData(BaseModel):
    partitions_count: int


class BrokerReplicaExclusionRequestData(BaseModel):
    broker_id: int
    reason: str


class BrokerReplicaExclusionBatchRequestData(BaseModel):
    data: List[BrokerReplicaExclusionRequestData]


class ConfigData(BaseModel):
    name: str
    value: str


class CreateLinkRequestData(BaseModel):
    source_cluster_id: Optional[str] = None
    destination_cluster_id: Optional[str] = None
    remote_cluster_id: Optional[str] = Field(
        None, description='The expected remote cluster ID.'
    )
    cluster_link_id: Optional[str] = Field(
        None,
        description="The expected cluster link ID. Can be provided when creating the second side of a bidirectional link for validating the link ID is as expected. If it's not provided, it's inferred from the remote cluster.",
    )
    configs: Optional[List[ConfigData]] = None


class UpdateLinkConfigRequestData(BaseModel):
    value: str


class LinkState(BaseModel):
    __root__: str


class LinkError(BaseModel):
    __root__: str


class StateCategory(BaseModel):
    __root__: str


class LinkTaskError(BaseModel):
    error_code: str
    error_message: str


class LinkTaskState(BaseModel):
    __root__: str


class LinkTaskErrorCode(BaseModel):
    __root__: str


class CreateMirrorTopicRequestData(BaseModel):
    source_topic_name: str
    mirror_topic_name: Optional[str] = None
    replication_factor: Optional[int] = None
    configs: Optional[List[ConfigData]] = None


class AlterMirrorsRequestData(BaseModel):
    mirror_topic_names: Optional[List[str]] = Field(
        None, description='The mirror topics specified as a list of topic names.'
    )
    mirror_topic_name_pattern: Optional[str] = Field(
        None, description='The mirror topics specified as a pattern.'
    )


class RemoveBrokersRequestData(BaseModel):
    broker_ids: List[int]


class PartitionLevelTruncationData(BaseModel):
    partition_id: int
    offset_truncated_to: int
    messages_truncated: int


class MirrorLag(BaseModel):
    partition: int
    lag: int
    last_source_fetch_offset: int


class MirrorTopicStatus(Enum):
    ACTIVE = 'ACTIVE'
    FAILED = 'FAILED'
    LINK_FAILED = 'LINK_FAILED'
    LINK_PAUSED = 'LINK_PAUSED'
    PAUSED = 'PAUSED'
    PENDING_STOPPED = 'PENDING_STOPPED'
    SOURCE_UNAVAILABLE = 'SOURCE_UNAVAILABLE'
    STOPPED = 'STOPPED'
    PENDING_MIRROR = 'PENDING_MIRROR'
    PENDING_SYNCHRONIZE = 'PENDING_SYNCHRONIZE'
    PENDING_SETUP_FOR_RESTORE = 'PENDING_SETUP_FOR_RESTORE'
    PENDING_RESTORE = 'PENDING_RESTORE'


class AnyUnevenLoadStatus(BaseModel):
    __root__: str


class BalancerStatus(BaseModel):
    __root__: str


class BrokerTaskType(Enum):
    add_broker = 'add-broker'
    remove_broker = 'remove-broker'


class BrokerTaskStatus(BaseModel):
    __root__: str


class ExclusionOp(BaseModel):
    __root__: str


class BrokerReplicaExclusionStatus(BaseModel):
    __root__: str


class DeprecatedPartitionReassignmentStatus(BaseModel):
    __root__: str


class DeprecatedBrokerShutdownStatus(BaseModel):
    __root__: str


class ClusterConfig(BaseModel):
    maxSchemas: Optional[int] = Field(
        None, description='Maximum number of registered schemas allowed', example=20000
    )
    maxRequestsPerSec: Optional[int] = Field(
        None, description='Maximum number of allowed requests per second', example=25
    )


class CompatibilityCheckResponse(BaseModel):
    is_compatible: Optional[bool] = Field(
        None, description='Whether the compared schemas are compatible'
    )
    messages: Optional[List[str]] = Field(
        None, description='Error messages', example=[]
    )


class ErrorMessage(BaseModel):
    error_code: Optional[int] = Field(None, description='The error code')
    message: Optional[str] = Field(None, description='The error message')


class ExporterUpdateRequest(BaseModel):
    contextType: Optional[str] = Field(
        None,
        description='Context type of the exporter. One of CUSTOM, NONE or AUTO (default)',
        example='CUSTOM',
    )
    context: Optional[str] = Field(
        None,
        description='Customized context of the exporter if contextType equals CUSTOM.',
        example='User',
    )
    subjects: Optional[List[str]] = Field(
        None, description='Name of each exporter subject'
    )
    kekRenameFormat: Optional[str] = Field(
        None,
        description='Format string for the KEK name in the destination cluster, which may\ncontain ${kek} as a placeholder for the originating KEK name. For\nexample, dc_${kek} for the KEK aws_key will map to the destination\nKEK name dc_aws_key.',
    )
    subjectRenameFormat: Optional[str] = Field(
        None,
        description='Format string for the subject name in the destination cluster, which\nmay contain ${subject} as a placeholder for the originating subject\nname. For example, dc_${subject} for the subject orders will map to\nthe destination subject name dc_orders.',
    )
    config: Optional[Dict[str, str]] = Field(
        None, description='The map containing exporter’s configurations'
    )


class ExporterStatusResponse(BaseModel):
    name: Optional[str] = Field(
        None, description='Name of exporter.', example='test-exporter'
    )
    state: Optional[str] = Field(
        None,
        description='State of the exporter. Could be STARTING, RUNNING or PAUSED',
        example='RUNNING',
    )
    offset: Optional[int] = Field(
        None, description='Offset of the exporter', example=100
    )
    ts: Optional[int] = Field(
        None, description='Timestamp of the exporter', example=1631206325
    )
    trace: Optional[str] = Field(
        None, description='Error trace of the exporter', example=''
    )


class ExporterConfigResponse(BaseModel):
    schema_registry_url: Optional[str] = Field(
        None,
        alias='schema.registry.url',
        description='Config SR URL',
        example='<Physical SR Endpoint>',
    )
    basic_auth_credentials_source: Optional[str] = Field(
        None,
        alias='basic.auth.credentials.source',
        description='Config SR Auth',
        example='USER_INFO',
    )
    basic_auth_user_info: Optional[str] = Field(
        None, alias='basic.auth.user.info', description='Config SR User Info'
    )


class SchemaReference(BaseModel):
    name: Optional[str] = Field(
        None, description='Reference name', example='io.confluent.kafka.example.User'
    )
    subject: Optional[str] = Field(
        None, description='Name of the referenced subject', example='User'
    )
    version: Optional[int] = Field(
        None, description='Version number of the referenced subject', example=1
    )


class ExporterReference(BaseModel):
    name: Optional[str] = Field(
        None, description='Name of the exporter', example='test-exporter'
    )
    contextType: Optional[str] = Field(
        None,
        description='Context type of the exporter. One of CUSTOM, NONE or AUTO (default)',
        example='CUSTOM',
    )
    context: Optional[str] = Field(
        None,
        description='Customized context of the exporter if contextType equals CUSTOM.',
        example='User',
    )
    subjects: Optional[List[str]] = Field(
        None, description='Name of each exporter subject'
    )
    kekRenameFormat: Optional[str] = Field(
        None,
        description='Format string for the KEK name in the destination cluster, which may contain ${kek} as a placeholder for the originating KEK name. For example, dc_${kek} for the KEK aws_key will map to the destination KEK name dc_aws_key.',
    )
    subjectRenameFormat: Optional[str] = Field(
        None,
        description='Format string for the subject name in the destination cluster, which may contain ${subject} as a placeholder for the originating subject name. For example, dc_${subject} for the subject orders will map to the destination subject name dc_orders.',
    )
    config: Optional[Dict[str, str]] = Field(
        None, description='The map containing exporter’s configurations'
    )


class DefaultMetadata(BaseModel):
    properties: Optional[Dict[str, Any]] = Field(
        None, description='The metadata properties and their new values'
    )


class OverrideMetadata(BaseModel):
    properties: Optional[Dict[str, Any]] = Field(
        None, description='The metadata properties and their new values'
    )


class DefaultRuleSet(BaseModel):
    properties: Optional[Dict[str, Any]] = Field(
        None, description='The metadata properties and their new values'
    )


class OverrideRuleSet(BaseModel):
    properties: Optional[Dict[str, Any]] = Field(
        None, description='The metadata properties and their new values'
    )


class Config1(BaseModel):
    alias: Optional[str] = Field(
        None,
        description='If alias is specified, then this subject is an alias for the subject\nnamed by the alias. That means that any reference to this subject\nwill be replaced by the alias.',
    )
    normalize: Optional[bool] = Field(
        None,
        description='If true, then schemas are automatically normalized when registered or\nwhen passed during lookups. This means that clients do not have to\npass the "normalize" query parameter to have normalization occur.',
    )
    compatibilityLevel: Optional[str] = Field(
        None, description='Compatibility Level', example='FULL_TRANSITIVE'
    )
    compatibilityGroup: Optional[str] = Field(
        None,
        description='Only schemas that belong to the same compatibility group will be\nchecked for compatibility.',
    )
    defaultMetadata: Optional[DefaultMetadata] = Field(
        None,
        description='Default value for the metadata to be used during schema registration.',
    )
    overrideMetadata: Optional[OverrideMetadata] = Field(
        None,
        description='Override value for the metadata to be used during schema registration.',
    )
    defaultRuleSet: Optional[DefaultRuleSet] = Field(
        None,
        description='Default value for the ruleSet to be used during schema registration.',
    )
    overrideRuleSet: Optional[OverrideRuleSet] = Field(
        None,
        description='Override value for the ruleSet to be used during schema registration.',
    )


class ConfigUpdateRequest(BaseModel):
    alias: Optional[str] = Field(
        None,
        description='If alias is specified, then this subject is an alias for the subject\nnamed by the alias. That means that any reference to this subject\nwill be replaced by the alias.',
    )
    normalize: Optional[bool] = Field(
        None,
        description='If true, then schemas are automatically normalized when registered\nor when passed during lookups. This means that clients do not have\nto pass the "normalize" query parameter to have normalization occur.',
    )
    compatibility: Optional[str] = Field(
        None, description='Compatibility Level', example='FULL_TRANSITIVE'
    )
    compatibilityGroup: Optional[str] = Field(
        None,
        description='Only schemas that belong to the same compatibility group will be\nchecked for compatibility.',
    )
    defaultMetadata: Optional[DefaultMetadata] = Field(
        None,
        description='Default value for the metadata to be used during schema registration.',
    )
    overrideMetadata: Optional[OverrideMetadata] = Field(
        None,
        description='Override value for the metadata to be used during schema registration.',
    )
    defaultRuleSet: Optional[DefaultRuleSet] = Field(
        None,
        description='Default value for the ruleSet to be used during schema registration.',
    )
    overrideRuleSet: Optional[OverrideRuleSet] = Field(
        None,
        description='Override value for the ruleSet to be used during schema registration.',
    )


class Mode(BaseModel):
    mode: Optional[str] = Field(
        None, description='Schema Registry operating mode', example='READWRITE'
    )


class ModeUpdateRequest(BaseModel):
    mode: Optional[str] = Field(
        None, description='Schema Registry operating mode', example='READWRITE'
    )


class SchemaString(BaseModel):
    schemaType: Optional[str] = Field(None, description='Schema type', example='AVRO')
    schema_: Optional[str] = Field(
        None,
        alias='schema',
        description='Schema string identified by the ID',
        example='{"schema": "{"type": "string"}"}',
    )
    references: Optional[List[SchemaReference]] = Field(
        None, description='References to other schemas'
    )
    maxId: Optional[int] = Field(None, description='Maximum ID', example=1)


class SubjectVersion(BaseModel):
    subject: Optional[str] = Field(
        None, description='Name of the subject', example='User'
    )
    version: Optional[int] = Field(None, description='Version number', example=1)


class ExporterResponse(BaseModel):
    name: Optional[str] = Field(
        None, description='Name of the exporter', example='test-exporter'
    )


class RegisterSchemaResponse(BaseModel):
    id: Optional[int] = Field(
        None, description='Globally unique identifier of the schema', example=100001
    )


class Algorithm(Enum):
    AES128_GCM = 'AES128_GCM'
    AES256_GCM = 'AES256_GCM'
    AES256_SIV = 'AES256_SIV'


class Dek(BaseModel):
    kekName: Optional[str] = Field(None, description='Kek name of the dek')
    subject: Optional[str] = Field(None, description='Subject of the dek')
    version: Optional[int] = Field(None, description='Version of the dek')
    algorithm: Optional[Algorithm] = Field(None, description='Algorithm of the dek')
    encryptedKeyMaterial: Optional[str] = Field(
        None, description='Encrypted key material of the dek'
    )
    keyMaterial: Optional[str] = Field(None, description='Raw key material of the dek')
    ts: Optional[int] = Field(None, description='Timestamp of the dek')
    deleted: Optional[bool] = Field(None, description='Whether the dek is deleted')


class CreateDekRequest(BaseModel):
    subject: Optional[str] = Field(None, description='Subject of the dek')
    version: Optional[int] = Field(None, description='Version of the dek')
    algorithm: Optional[Algorithm] = Field(None, description='Algorithm of the dek')
    encryptedKeyMaterial: Optional[str] = Field(
        None, description='Encrypted key material of the dek'
    )
    deleted: Optional[bool] = Field(None, description='Whether the dek is deleted')


class Kek(BaseModel):
    name: Optional[str] = Field(None, description='Name of the kek')
    kmsType: Optional[str] = Field(None, description='KMS type of the kek')
    kmsKeyId: Optional[str] = Field(None, description='KMS key ID of the kek')
    kmsProps: Optional[Dict[str, str]] = Field(
        None, description='Properties of the kek'
    )
    doc: Optional[str] = Field(None, description='Description of the kek')
    shared: Optional[bool] = Field(None, description='Whether the kek is shared')
    ts: Optional[int] = Field(None, description='Timestamp of the kek')
    deleted: Optional[bool] = Field(None, description='Whether the kek is deleted')


class CreateKekRequest(BaseModel):
    name: Optional[str] = Field(None, description='Name of the kek')
    kmsType: Optional[str] = Field(None, description='KMS type of the kek')
    kmsKeyId: Optional[str] = Field(None, description='KMS key ID of the kek')
    kmsProps: Optional[Dict[str, str]] = Field(
        None, description='Properties of the kek'
    )
    doc: Optional[str] = Field(None, description='Description of the kek')
    shared: Optional[bool] = Field(None, description='Whether the kek is shared')
    deleted: Optional[bool] = Field(None, description='Whether the kek is deleted')


class UpdateKekRequest(BaseModel):
    kmsProps: Optional[Dict[str, str]] = Field(
        None, description='Properties of the kek'
    )
    doc: Optional[str] = Field(None, description='Description of the kek')
    shared: Optional[bool] = Field(None, description='Whether the kek is shared')


class Metadata(BaseModel):
    tags: Optional[Dict[str, List[str]]] = None
    properties: Optional[Dict[str, str]] = None
    sensitive: Optional[List[str]] = Field(None, unique_items=True)


class Kind(Enum):
    TRANSFORM = 'TRANSFORM'
    CONDITION = 'CONDITION'


class Mode1(Enum):
    UPGRADE = 'UPGRADE'
    DOWNGRADE = 'DOWNGRADE'
    UPDOWN = 'UPDOWN'
    WRITE = 'WRITE'
    READ = 'READ'
    WRITEREAD = 'WRITEREAD'


class Rule(BaseModel):
    name: Optional[str] = Field(None, description='Rule name')
    doc: Optional[str] = Field(None, description='Rule doc')
    kind: Optional[Kind] = Field(None, description='Rule kind')
    mode: Optional[Mode1] = Field(None, description='Rule mode')
    type: Optional[str] = Field(None, description='Rule type')
    tags: Optional[List[str]] = Field(
        None, description='The tags to which this rule applies', unique_items=True
    )
    params: Optional[Dict[str, str]] = Field(
        None, description='Optional params for the rule'
    )
    expr: Optional[str] = Field(None, description='Rule expression')
    onSuccess: Optional[str] = Field(None, description='Rule action on success')
    onFailure: Optional[str] = Field(None, description='Rule action on failure')
    disabled: Optional[bool] = Field(None, description='Whether the rule is disabled')


class EntityType(Enum):
    sr_record = 'sr_record'
    sr_field = 'sr_field'


class SchemaEntity(BaseModel):
    entityPath: Optional[str] = None
    entityType: Optional[EntityType] = None


class SchemaTags(BaseModel):
    schemaEntity: Optional[SchemaEntity] = None
    tags: Optional[List[str]] = None


class EntityStatus(Enum):
    ACTIVE = 'ACTIVE'
    DELETED = 'DELETED'
    PURGED = 'PURGED'


class TimeBoundary(BaseModel):
    startTime: Optional[str] = Field(
        None, description='The start time of format yyyy/MM/dd HH:mm:ss'
    )
    endTime: Optional[str] = Field(
        None, description='The end time of format yyyy/MM/dd HH:mm:ss'
    )
    timeZone: Optional[str] = Field(
        None, description='The time zone (see java.util.TimeZone)'
    )


class Classification(BaseModel):
    typeName: Optional[str] = Field(None, description='The tag name')
    attributes: Optional[Dict[str, Dict[str, Any]]] = Field(
        None, description='The tag attributes'
    )
    entityGuid: Optional[str] = Field(None, description='The internal entity guid')
    entityStatus: Optional[EntityStatus] = Field(None, description='The entity status')
    propagate: Optional[bool] = Field(None, description='Whether to propagate the tag')
    validityPeriods: Optional[List[TimeBoundary]] = Field(
        None, description='The validity periods'
    )
    removePropagationsOnEntityDelete: Optional[bool] = Field(
        None, description='Whether to remove propagations on entity delete'
    )


class ClassificationHeader(BaseModel):
    typeName: Optional[str] = Field(None, description='The tag name')
    entityGuid: Optional[str] = Field(None, description='The internal entity guid')
    entityStatus: Optional[EntityStatus] = Field(None, description='The entity status')
    propagate: Optional[bool] = Field(None, description='Whether to propagate the tag')
    removePropagationsOnEntityDelete: Optional[bool] = Field(
        None, description='Whether to remove propagations on entity delete'
    )


class Status(Enum):
    ACTIVE = 'ACTIVE'
    DELETED = 'DELETED'
    PURGED = 'PURGED'


class Status1(Enum):
    DISCOVERED = 'DISCOVERED'
    PROPOSED = 'PROPOSED'
    IMPORTED = 'IMPORTED'
    VALIDATED = 'VALIDATED'
    DEPRECATED = 'DEPRECATED'
    OBSOLETE = 'OBSOLETE'
    OTHER = 'OTHER'


class TermAssignmentHeader(BaseModel):
    termGuid: Optional[str] = Field(None, description='The term guid')
    relationGuid: Optional[str] = Field(None, description='The relation guid')
    description: Optional[str] = Field(None, description='The description')
    displayText: Optional[str] = Field(None, description='The display text')
    expression: Optional[str] = Field(None, description='The expression')
    createdBy: Optional[str] = Field(None, description='The creator')
    steward: Optional[str] = Field(None, description='The steward')
    source: Optional[str] = Field(None, description='The source')
    confidence: Optional[int] = Field(None, description='The confidence')
    status: Optional[Status1] = Field(None, description='The status')


class Status2(Enum):
    ACTIVE = 'ACTIVE'
    DELETED = 'DELETED'
    PURGED = 'PURGED'


class EntityHeader(BaseModel):
    typeName: Optional[str] = Field(None, description='The type name')
    attributes: Optional[Dict[str, Any]] = Field(None, description='The attributes')
    guid: Optional[str] = Field(None, description='The internal guid')
    status: Optional[Status2] = Field(None, description='The status')
    displayText: Optional[str] = Field(None, description='The display text')
    classificationNames: Optional[List[str]] = Field(
        None, description='The classification (tag) names'
    )
    classifications: Optional[List[Classification]] = Field(
        None, description='The classifications (tags)'
    )
    meaningNames: Optional[List[str]] = Field(None, description='The meaning names')
    meanings: Optional[List[TermAssignmentHeader]] = Field(
        None, description='The meanings'
    )
    isIncomplete: Optional[bool] = Field(None, description='Whether is incomplete')
    labels: Optional[List[str]] = Field(
        None, description='The labels', unique_items=True
    )


class PartialUpdateParams(BaseModel):
    typeName: Optional[str] = Field(None, description='The type name')
    attributes: Optional[Dict[str, Any]] = Field(None, description='The attributes')
    guid: Optional[str] = Field(None, description='The internal guid')
    status: Optional[Status2] = Field(None, description='The status')
    classificationNames: Optional[List[str]] = Field(
        None, description='The classification (tag) names'
    )
    classifications: Optional[List[ClassificationHeader]] = Field(
        None, description='The classifications (tags)'
    )
    isIncomplete: Optional[bool] = Field(None, description='Whether is incomplete')


class SearchParams(BaseModel):
    includeDeleted: Optional[bool] = Field(
        None, description='Whether to include deleted'
    )
    limit: Optional[int] = Field(None, description='The limit')
    offset: Optional[int] = Field(None, description='The offset')


class SearchResult(BaseModel):
    searchParameters: Optional[SearchParams] = None
    types: Optional[List[str]] = Field(None, description='The types')
    entities: Optional[List[EntityHeader]] = Field(None, description='The entities')
    referredEntities: Optional[Dict[str, EntityHeader]] = Field(
        None, description='The referred entities'
    )


class Cardinality(Enum):
    SINGLE = 'SINGLE'
    LIST = 'LIST'
    SET = 'SET'


class IndexType(Enum):
    DEFAULT = 'DEFAULT'
    STRING = 'STRING'


class ConstraintDef(BaseModel):
    type: Optional[str] = Field(None, description='The type')
    params: Optional[Dict[str, Dict[str, Any]]] = Field(None, description='The params')


class Category(Enum):
    PRIMITIVE = 'PRIMITIVE'
    OBJECT_ID_TYPE = 'OBJECT_ID_TYPE'
    ENUM = 'ENUM'
    STRUCT = 'STRUCT'
    CLASSIFICATION = 'CLASSIFICATION'
    ENTITY = 'ENTITY'
    ARRAY = 'ARRAY'
    MAP = 'MAP'
    RELATIONSHIP = 'RELATIONSHIP'
    BUSINESS_METADATA = 'BUSINESS_METADATA'


class BusinessMetadataResponse(BaseModel):
    typeName: Optional[str] = Field(None, description='The business metadata name')
    attributes: Optional[Dict[str, Any]] = Field(
        None, description='The business metadata attributes'
    )
    entityType: Optional[str] = Field(None, description='The entity type')
    entityName: Optional[str] = Field(
        None, description='The qualified name of the entity'
    )
    error: Optional[ErrorMessage] = None


class BusinessMetadata(BaseModel):
    typeName: Optional[str] = Field(None, description='The business metadata name')
    attributes: Optional[Dict[str, Any]] = Field(
        None, description='The business metadata attributes'
    )
    entityType: Optional[str] = Field(None, description='The entity type')
    entityName: Optional[str] = Field(
        None, description='The qualified name of the entity'
    )


class TagResponse(BaseModel):
    typeName: Optional[str] = Field(None, description='The tag name')
    attributes: Optional[Dict[str, Any]] = Field(None, description='The tag attributes')
    entityGuid: Optional[str] = Field(None, description='The internal entity guid')
    entityStatus: Optional[EntityStatus] = Field(None, description='The entity status')
    propagate: Optional[bool] = Field(None, description='Whether to propagate the tag')
    validityPeriods: Optional[List[TimeBoundary]] = Field(
        None, description='The validity periods'
    )
    removePropagationsOnEntityDelete: Optional[bool] = Field(
        None, description='Whether to remove propagations on entity delete'
    )
    entityType: Optional[str] = Field(None, description='The entity type')
    entityName: Optional[str] = Field(
        None, description='The qualified name of the entity'
    )
    error: Optional[ErrorMessage] = None


class BooleanFilter(BaseModel):
    __root__: bool = Field(
        ..., description='Filter for whether this value is true or false.'
    )


class AzureSSOConfig(BaseModel):
    kind: Literal['AzureSSOConfig'] = Field(..., example='AzureSSOConfig')
    tenant_id: str = Field(
        ...,
        description='The Azure AD tenant ID',
        example='b3a17773-05cc-4431-9560-433fb4613da8',
    )


class PartnerSignupResponse(BaseModel):
    organization_id: str = Field(
        ...,
        description='The ID of the organization',
        example='b3a17773-05cc-4431-9560-433fb4613da8',
    )
    sso_url: AnyUrl = Field(
        ...,
        description='The login URL for the customer to access Confluent Cloud',
        example='https://confluent.cloud/login/sso/AzureAD-OIDC-Conn',
    )
    display_message: Optional[str] = Field(
        None,
        description='The display message contains useful information which is shown on the Marketplace UI to the customers.',
        example='Your support plan will remain the same, to change the plan, follow this [link](https://docs.confluent.io/cloud/current/faq.html#how-do-i-change-support-plans).',
    )


class CostListMeta(BaseModel):
    next: Optional[AnyUrl] = Field(
        None,
        description='A link to the next page of results. If a response does not contain a next link, then there is no more data available.',
        example='https://api.confluent.cloud/v2/resourcekinds?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class StatementObjectMeta(BaseModel):
    self: AnyUrl = Field(
        ...,
        description='Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the service location, API version, and other particulars necessary to locate the resource at a point in time',
        example='https://flink.us-west1.aws.confluent.cloud/sql/v1/environments/env-123/statements/my-statement',
    )
    created_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.',
        example='1996-03-19T01:02:03-04:05',
    )
    updated_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was last updated. It is represented in RFC3339 format and is in UTC.',
        example='2023-03-31T00:00:00-00:00',
    )
    uid: Optional[str] = Field(
        None,
        description='A system generated globally unique identifier for this resource.',
        example='12345678-1234-1234-1234-123456789012',
    )
    resource_version: Optional[str] = Field(
        None,
        description='A system generated string that uniquely identifies the version of this resource.',
        example='a23av',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='A map of key-value pairs that describe the resource.',
        example={'user.confluent.io/hidden': 'true'},
    )


class ResultListMeta(BaseModel):
    self: Optional[str] = Field(
        None,
        description='Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the service location, API version, and other particulars necessary to locate the resource at a point in time',
        example='https://flink.us-west1.aws.confluent.cloud/sql/v1/environments/env-123/statements',
    )
    next: Optional[str] = Field(
        None,
        description='A URL that can be followed to get the next batch of results.',
        example='https://flink.us-west1.aws.confluent.cloud/sql/v1/environments/env-abc123/statements?page_token=UvmDWOB1iwfAIBPj6EYb',
    )
    created_at: Optional[datetime] = Field(
        None,
        description='The date and time at which this object was created. It is represented in RFC3339 format and is in UTC.',
        example='2006-01-02T15:04:05-07:00',
    )


class ExceptionListMeta(BaseModel):
    self: Optional[str] = Field(
        None,
        description='Self is a Uniform Resource Locator (URL) at which an object can be addressed. This URL encodes the service location, API version, and other particulars necessary to locate the resource at a point in time',
        example='https://flink.us-west1.aws.confluent.cloud/sql/v1/environments/env-123/statements/sql123/exceptions',
    )


class Op(Enum):
    ADD = 'ADD'
    REPLACE = 'REPLACE'
    TEST = 'TEST'


class JsonPatchRequestAddReplace(BaseModel):
    class Config:
        extra = Extra.forbid

    path: str = Field(..., description='A JSON Pointer path.')
    value: Any = Field(..., description='The value to add, replace or test.')
    op: Op = Field(..., description='The operation to perform.')


class Op1(Enum):
    REMOVE = 'REMOVE'


class JsonPatchRequestRemove(BaseModel):
    class Config:
        extra = Extra.forbid

    path: str = Field(..., description='A JSON Pointer path.')
    op: Op1 = Field(..., description='The operation to perform.')


class Op2(Enum):
    MOVE = 'MOVE'
    COPY = 'COPY'


class JsonPatchRequestMoveCopy(BaseModel):
    class Config:
        extra = Extra.forbid

    path: str = Field(..., description='A JSON Pointer path.')
    op: Op2 = Field(..., description='The operation to perform.')
    from_: str = Field(..., alias='from', description='A JSON Pointer path.')


class Failure(BaseModel):
    errors: List[Error] = Field(
        ...,
        description='List of errors which caused this operation to fail',
        unique_items=True,
    )


class ProduceResponse(BaseModel):
    error_code: int
    message: Optional[str] = None
    cluster_id: Optional[str] = None
    topic_name: Optional[str] = None
    partition_id: Optional[int] = None
    offset: Optional[int] = None
    timestamp: Optional[datetime] = None
    key: Optional[ProduceResponseData] = None
    value: Optional[ProduceResponseData] = None


class ProduceRequest(BaseModel):
    partition_id: Optional[int] = None
    headers: Optional[List[ProduceRequestHeader]] = None
    key: Optional[ProduceRequestData] = None
    value: Optional[ProduceRequestData] = None
    timestamp: Optional[datetime] = None


class Resource(BaseModel):
    kind: str
    metadata: ResourceMetadata


class ResourceCollection(BaseModel):
    kind: str
    metadata: ResourceCollectionMetadata


class TopicData(Resource):
    cluster_id: str
    topic_name: str
    is_internal: bool
    replication_factor: int
    partitions_count: int
    partitions: Relationship
    configs: Relationship
    partition_reassignments: Relationship
    authorized_operations: Optional[AuthorizedOperations] = None


class TopicDataList(ResourceCollection):
    data: List[TopicData]


class ReplicaStatusData(Resource):
    cluster_id: str
    topic_name: str
    broker_id: int
    partition_id: int
    is_leader: bool
    is_observer: bool
    is_isr_eligible: bool
    is_in_isr: bool
    is_caught_up: bool
    log_start_offset: int
    log_end_offset: int
    last_caught_up_time_ms: int
    last_fetch_time_ms: int
    link_name: Optional[str] = None


class ReplicaStatusDataList(ResourceCollection):
    data: List[ReplicaStatusData]


class AnyUnevenLoadData(Resource):
    cluster_id: str
    status: AnyUnevenLoadStatus
    previous_status: AnyUnevenLoadStatus
    status_updated_at: datetime = Field(
        ...,
        description='The date and time at which this task was created.',
        example='2019-10-12T07:20:50Z',
    )
    previous_status_updated_at: datetime = Field(
        ...,
        description='The date and time at which this task was created.',
        example='2019-10-12T07:20:50Z',
    )
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    broker_tasks: Relationship


class BalancerStatusData(Resource):
    cluster_id: str
    status: BalancerStatus
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    any_uneven_load: Relationship
    broker_tasks: Relationship


class BrokerRemovalData(Resource):
    cluster_id: str
    broker_id: int
    broker_task: Relationship
    broker: Relationship


class BrokerRemovalDataList(ResourceCollection):
    data: List[BrokerRemovalData]


class BrokerTaskData(Resource):
    cluster_id: str
    broker_id: int
    task_type: BrokerTaskType
    task_status: BrokerTaskStatus
    shutdown_scheduled: Optional[bool] = None
    sub_task_statuses: Dict[str, str]
    created_at: datetime = Field(
        ...,
        description='The date and time at which this task was created.',
        example='2019-10-12T07:20:50Z',
    )
    updated_at: datetime = Field(
        ...,
        description='The date and time at which this task was last updated.',
        example='2019-10-12T07:20:50Z',
    )
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    broker: Relationship


class BrokerTaskDataList(ResourceCollection):
    data: List[BrokerTaskData]


class BrokerReplicaExclusionData(Resource):
    cluster_id: str
    broker_id: int
    reason: str
    broker: Relationship


class BrokerReplicaExclusionDataList(ResourceCollection):
    data: List[BrokerReplicaExclusionData]


class AlterBrokerReplicaExclusionData(Resource):
    cluster_id: str
    broker_id: int
    exclusion: ExclusionOp
    reason: str
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    broker: Relationship


class AlterBrokerReplicaExclusionDataList(ResourceCollection):
    data: List[AlterBrokerReplicaExclusionData]


class RemoveBrokerTaskData(Resource):
    cluster_id: str
    broker_id: int
    shutdown_scheduled: bool
    broker_replica_exclusion_status: BrokerReplicaExclusionStatus
    partition_reassignment_status: DeprecatedPartitionReassignmentStatus
    broker_shutdown_status: DeprecatedBrokerShutdownStatus
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    broker: Relationship


class RemoveBrokerTaskDataList(ResourceCollection):
    data: List[RemoveBrokerTaskData]


class LinkTask(BaseModel):
    task_name: str
    state: LinkTaskState
    errors: List[LinkTaskError]


class LinkCategory(BaseModel):
    state_category: StateCategory
    count: int = Field(..., example=123)


class ListLinksResponseData(Resource):
    source_cluster_id: Optional[str] = None
    destination_cluster_id: Optional[str] = None
    remote_cluster_id: Optional[str] = None
    link_name: str
    link_id: Optional[str] = None
    cluster_link_id: str
    topic_names: List[str]
    link_error: Optional[LinkError] = None
    link_error_message: Optional[str] = None
    link_state: Optional[LinkState] = None
    tasks: Optional[List[LinkTask]] = None
    category_counts: Optional[List[LinkCategory]] = None


class ListLinksResponseDataList(ResourceCollection):
    data: List[ListLinksResponseData]


class ListLinkConfigsResponseData(Resource):
    cluster_id: str
    name: str
    value: str
    is_default: bool
    is_read_only: bool
    is_sensitive: bool
    source: str
    synonyms: List[str]
    link_name: str


class ListLinkConfigsResponseDataList(ResourceCollection):
    data: List[ListLinkConfigsResponseData]


class PartitionLevelTruncationDataList(BaseModel):
    __root__: List[PartitionLevelTruncationData]


class MirrorLags(BaseModel):
    __root__: List[MirrorLag]


class RegisterExporterRequest(BaseModel):
    references: Optional[List[ExporterReference]] = Field(
        None, description='References to other schemas'
    )


class RuleSet(BaseModel):
    migrationRules: Optional[List[Rule]] = None
    domainRules: Optional[List[Rule]] = None


class Tag(BaseModel):
    typeName: Optional[str] = Field(None, description='The tag name')
    attributes: Optional[Dict[str, Any]] = Field(None, description='The tag attributes')
    entityGuid: Optional[str] = Field(None, description='The internal entity guid')
    entityStatus: Optional[EntityStatus] = Field(None, description='The entity status')
    propagate: Optional[bool] = Field(None, description='Whether to propagate the tag')
    validityPeriods: Optional[List[TimeBoundary]] = Field(
        None, description='The validity periods'
    )
    removePropagationsOnEntityDelete: Optional[bool] = Field(
        None, description='Whether to remove propagations on entity delete'
    )
    entityType: Optional[str] = Field(None, description='The entity type')
    entityName: Optional[str] = Field(
        None, description='The qualified name of the entity'
    )


class Entity(BaseModel):
    typeName: Optional[str] = Field(None, description='The type name')
    attributes: Optional[Dict[str, Any]] = Field(
        None, description='The type attributes'
    )
    guid: Optional[str] = Field(None, description='The internal guid')
    homeId: Optional[str] = Field(None, description='The home id')
    isProxy: Optional[bool] = Field(None, description='Whether is a proxy')
    isIncomplete: Optional[bool] = Field(None, description='Whether is incomplete')
    provenanceType: Optional[int] = Field(None, description='The provenance type')
    status: Optional[Status] = Field(None, description='The status')
    createdBy: Optional[str] = Field(None, description='The creator')
    updatedBy: Optional[str] = Field(None, description='The updater')
    createTime: Optional[int] = Field(None, description='The create time')
    updateTime: Optional[int] = Field(None, description='The update time')
    version: Optional[int] = Field(None, description='The version')
    relationshipAttributes: Optional[Dict[str, Any]] = Field(
        None, description='The relationship attributes'
    )
    classifications: Optional[List[Classification]] = Field(
        None, description='The classifications (tags)'
    )
    meanings: Optional[List[TermAssignmentHeader]] = Field(
        None, description='The meanings'
    )
    customAttributes: Optional[Dict[str, str]] = Field(
        None, description='The custom attributes'
    )
    businessAttributes: Optional[Dict[str, Dict[str, Any]]] = Field(
        None, description='The business attributes'
    )
    labels: Optional[List[str]] = Field(
        None, description='The labels', unique_items=True
    )
    proxy: Optional[bool] = Field(None, description='Whether is a proxy')


class EntityWithExtInfo(BaseModel):
    referredEntities: Optional[Dict[str, Entity]] = Field(
        None, description='The referred entities'
    )
    entity: Optional[Entity] = None


class EntityPartialUpdate(BaseModel):
    UPDATE: Optional[List[PartialUpdateParams]] = Field(
        None, description='The updated entities.'
    )


class AttributeDef(BaseModel):
    name: Optional[str] = Field(None, description='The name')
    typeName: Optional[str] = Field(None, description='The type name')
    isOptional: Optional[bool] = Field(None, description='Whether is optional')
    cardinality: Optional[Cardinality] = Field(None, description='The cardinality')
    valuesMinCount: Optional[int] = Field(None, description='The values min count')
    valuesMaxCount: Optional[int] = Field(None, description='The values max count')
    isUnique: Optional[bool] = Field(None, description='Whether is unique')
    isIndexable: Optional[bool] = Field(None, description='Whether is indexable')
    includeInNotification: Optional[bool] = Field(
        None, description='Whether to include in notifications'
    )
    defaultValue: Optional[str] = Field(None, description='The default value')
    description: Optional[str] = Field(None, description='The description')
    searchWeight: Optional[int] = Field(None, description='The search weight')
    indexType: Optional[IndexType] = Field(None, description='The index type')
    constraints: Optional[List[ConstraintDef]] = Field(
        None, description='The constraints'
    )
    options: Optional[Dict[str, str]] = Field(None, description='The options')
    displayName: Optional[str] = Field(None, description='The display name')


class TagDef(BaseModel):
    category: Optional[Category] = Field(None, description='The category')
    guid: Optional[str] = Field(None, description='The internal guid')
    createdBy: Optional[str] = Field(None, description='The creator')
    updatedBy: Optional[str] = Field(None, description='The updater')
    createTime: Optional[int] = Field(None, description='The create time')
    updateTime: Optional[int] = Field(None, description='The update time')
    version: Optional[int] = Field(None, description='The version')
    name: Optional[str] = Field(None, description='The name')
    description: Optional[str] = Field(None, description='The description')
    typeVersion: Optional[str] = Field(None, description='The type version')
    serviceType: Optional[str] = Field(None, description='The service type')
    options: Optional[Dict[str, str]] = Field(None, description='The options')
    attributeDefs: Optional[List[AttributeDef]] = Field(
        None, description='The attribute definitions'
    )
    superTypes: Optional[List[str]] = Field(
        None, description='The supertypes', unique_items=True
    )
    entityTypes: Optional[List[str]] = Field(
        None, description='The entity types', unique_items=True
    )
    subTypes: Optional[List[str]] = Field(
        None, description='The subtypes', unique_items=True
    )


class BusinessMetadataDefResponse(BaseModel):
    category: Optional[Category] = Field(None, description='The category')
    guid: Optional[str] = Field(None, description='The internal guid')
    createdBy: Optional[str] = Field(None, description='The creator')
    updatedBy: Optional[str] = Field(None, description='The updater')
    createTime: Optional[int] = Field(None, description='The create time')
    updateTime: Optional[int] = Field(None, description='The update time')
    version: Optional[int] = Field(None, description='The version')
    name: Optional[str] = Field(None, description='The name')
    description: Optional[str] = Field(None, description='The description')
    typeVersion: Optional[str] = Field(None, description='The type version')
    serviceType: Optional[str] = Field(None, description='The service type')
    options: Optional[Dict[str, str]] = Field(None, description='The options')
    attributeDefs: Optional[List[AttributeDef]] = Field(
        None, description='The attribute definitions'
    )
    error: Optional[ErrorMessage] = None


class BusinessMetadataDef(BaseModel):
    category: Optional[Category] = Field(None, description='The category')
    guid: Optional[str] = Field(None, description='The internal guid')
    createdBy: Optional[str] = Field(None, description='The creator')
    updatedBy: Optional[str] = Field(None, description='The updater')
    createTime: Optional[int] = Field(None, description='The create time')
    updateTime: Optional[int] = Field(None, description='The update time')
    version: Optional[int] = Field(None, description='The version')
    name: Optional[str] = Field(None, description='The name')
    description: Optional[str] = Field(None, description='The description')
    typeVersion: Optional[str] = Field(None, description='The type version')
    serviceType: Optional[str] = Field(None, description='The service type')
    options: Optional[Dict[str, str]] = Field(None, description='The options')
    attributeDefs: Optional[List[AttributeDef]] = Field(
        None, description='The attribute definitions'
    )


class TagDefResponse(BaseModel):
    category: Optional[Category] = Field(None, description='The category')
    guid: Optional[str] = Field(None, description='The internal guid')
    createdBy: Optional[str] = Field(None, description='The creator')
    updatedBy: Optional[str] = Field(None, description='The updater')
    createTime: Optional[int] = Field(None, description='The create time')
    updateTime: Optional[int] = Field(None, description='The update time')
    version: Optional[int] = Field(None, description='The version')
    name: Optional[str] = Field(None, description='The name')
    description: Optional[str] = Field(None, description='The description')
    typeVersion: Optional[str] = Field(None, description='The type version')
    serviceType: Optional[str] = Field(None, description='The service type')
    options: Optional[Dict[str, str]] = Field(None, description='The options')
    attributeDefs: Optional[List[AttributeDef]] = Field(
        None, description='The attribute definitions'
    )
    superTypes: Optional[List[str]] = Field(
        None, description='The supertypes', unique_items=True
    )
    entityTypes: Optional[List[str]] = Field(
        None, description='The entity types', unique_items=True
    )
    subTypes: Optional[List[str]] = Field(
        None, description='The subtypes', unique_items=True
    )
    error: Optional[ErrorMessage] = None


class PartnerSignupRequest(BaseModel):
    organization: v2.Organization
    user: Optional[v2_1.User] = None
    entitlement: Union[v2.Entitlement, ObjectReference]


class ActivatePartnerSignupRequest(BaseModel):
    user: v2_1.User
    organization_id: str = Field(
        ...,
        description='The ID of the organization',
        example='b3a17773-05cc-4431-9560-433fb4613da8',
    )


class PartnerLinkRequest(BaseModel):
    token: str = Field(
        ...,
        description='The linking token that was generated.',
        example='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    )
    organization: v2.Organization
    entitlement: Union[v2.Entitlement, ObjectReference]


class PatchRequest(BaseModel):
    __root__: List[
        Union[
            JsonPatchRequestAddReplace, JsonPatchRequestRemove, JsonPatchRequestMoveCopy
        ]
    ] = Field(
        ...,
        description='PatchRequest represent a json-patch request to be applied to the Statement. See https://tools.ietf.org/html/rfc6902',
    )


class AbstractConfigData(Resource):
    cluster_id: str
    name: str
    value: Optional[str] = None
    is_default: bool
    is_read_only: bool
    is_sensitive: bool
    source: ConfigSource
    synonyms: List[ConfigSynonymData]


class AclData(Resource):
    cluster_id: str
    resource_type: AclResourceType
    resource_name: str
    pattern_type: AclPatternType
    principal: str
    host: str
    operation: AclOperation
    permission: AclPermission


class AclDataList(ResourceCollection):
    data: List[AclData]


class BrokerConfigData(AbstractConfigData):
    broker_id: int


class BrokerConfigDataList(ResourceCollection):
    data: List[BrokerConfigData]


class BrokerData(Resource):
    cluster_id: str
    broker_id: int
    host: Optional[str] = None
    port: Optional[int] = None
    rack: Optional[str] = None
    configs: Relationship
    partition_replicas: Relationship


class BrokerDataList(ResourceCollection):
    data: List[BrokerData]


class ClusterConfigData(AbstractConfigData):
    config_type: ClusterConfigType


class ClusterConfigDataList(ResourceCollection):
    data: List[ClusterConfigData]


class ClusterData(Resource):
    cluster_id: str
    controller: Optional[Relationship] = None
    acls: Relationship
    brokers: Relationship
    broker_configs: Relationship
    consumer_groups: Relationship
    topics: Relationship
    partition_reassignments: Relationship


class ClusterDataList(ResourceCollection):
    data: List[ClusterData]


class ConsumerAssignmentData(Resource):
    cluster_id: str
    consumer_group_id: str
    consumer_id: str
    topic_name: str
    partition_id: int
    partition: Relationship
    lag: Relationship


class ConsumerAssignmentDataList(ResourceCollection):
    data: List[ConsumerAssignmentData]


class ConsumerData(Resource):
    cluster_id: str
    consumer_group_id: str
    consumer_id: str
    instance_id: Optional[str] = None
    client_id: str
    assignments: Relationship


class ConsumerDataList(ResourceCollection):
    data: List[ConsumerData]


class ConsumerGroupData(Resource):
    cluster_id: str
    consumer_group_id: str
    is_simple: bool
    partition_assignor: str
    state: ConsumerGroupState
    type: ConsumerGroupType
    is_mixed_consumer_group: bool
    coordinator: Relationship
    consumers: Relationship
    lag_summary: Relationship


class ConsumerGroupDataList(ResourceCollection):
    data: List[ConsumerGroupData]


class ConsumerLagData(Resource):
    cluster_id: str
    consumer_group_id: str
    topic_name: str
    partition_id: int
    current_offset: int
    log_end_offset: int
    lag: int
    consumer_id: str
    instance_id: Optional[str] = None
    client_id: str


class ConsumerLagDataList(ResourceCollection):
    data: List[ConsumerLagData]


class ConsumerGroupLagSummaryData(Resource):
    cluster_id: str
    consumer_group_id: str
    max_lag_consumer_id: str
    max_lag_instance_id: Optional[str] = None
    max_lag_client_id: str
    max_lag_topic_name: str
    max_lag_partition_id: int
    max_lag: int
    total_lag: int
    max_lag_consumer: Relationship
    max_lag_partition: Relationship


class PartitionData(Resource):
    cluster_id: str
    topic_name: str
    partition_id: int
    leader: Optional[Relationship] = None
    replicas: Relationship
    reassignment: Relationship


class PartitionDataList(ResourceCollection):
    data: List[PartitionData]


class ReassignmentData(Resource):
    cluster_id: str
    topic_name: str
    partition_id: int
    adding_replicas: List[int]
    removing_replicas: List[int]
    replicas: Relationship


class ReassignmentDataList(ResourceCollection):
    data: List[ReassignmentData]


class ReplicaData(Resource):
    cluster_id: str
    topic_name: str
    partition_id: int
    broker_id: int
    is_leader: bool
    is_in_sync: bool
    broker: Relationship


class ReplicaDataList(ResourceCollection):
    data: List[ReplicaData]


class TopicConfigData(AbstractConfigData):
    topic_name: str


class TopicConfigDataList(ResourceCollection):
    data: List[TopicConfigData]


class ListMirrorTopicsResponseData(Resource):
    link_name: str
    mirror_topic_name: str
    source_topic_name: str
    num_partitions: int
    mirror_lags: MirrorLags
    mirror_status: MirrorTopicStatus
    state_time_ms: int
    mirror_state_transition_errors: Optional[List[LinkTaskError]] = None


class ListMirrorTopicsResponseDataList(ResourceCollection):
    data: List[ListMirrorTopicsResponseData]


class AlterMirrorStatusResponseData(Resource):
    mirror_topic_name: str
    error_message: str
    error_code: int
    mirror_lags: MirrorLags
    messages_truncated: int
    partition_level_truncation_data: PartitionLevelTruncationDataList


class AlterMirrorStatusResponseDataList(ResourceCollection):
    data: List[AlterMirrorStatusResponseData]


class RegisterSchemaRequest(BaseModel):
    version: Optional[int] = Field(None, description='Version number')
    id: Optional[int] = Field(
        None, description='Globally unique identifier of the schema'
    )
    schemaType: Optional[str] = Field(None, description='Schema type')
    references: Optional[List[SchemaReference]] = Field(
        None, description='References to other schemas'
    )
    schema_: Optional[str] = Field(
        None, alias='schema', description='Schema definition string'
    )
    metadata: Optional[Metadata] = None
    ruleSet: Optional[RuleSet] = None
    schemaTagsToAdd: Optional[List[SchemaTags]] = None
    schemaTagsToRemove: Optional[List[SchemaTags]] = None
    propagateSchemaTags: Optional[bool] = None


class Schema(BaseModel):
    subject: Optional[str] = Field(
        None, description='Name of the subject', example='User'
    )
    version: Optional[int] = Field(None, description='Version number', example=1)
    id: Optional[int] = Field(
        None, description='Globally unique identifier of the schema', example=100001
    )
    schemaType: Optional[str] = Field(None, description='Schema type', example='AVRO')
    references: Optional[List[SchemaReference]] = Field(
        None, description='References to other schemas'
    )
    schema_: Optional[str] = Field(
        None,
        alias='schema',
        description='Schema definition string',
        example='{"schema": "{"type": "string"}"}',
    )
    metadata: Optional[Metadata] = None
    ruleSet: Optional[RuleSet] = None


class EntityPartialUpdateResponse(BaseModel):
    mutatedEntities: Optional[EntityPartialUpdate] = None


class ColumnDetails(BaseModel):
    name: str = Field(
        ..., description='The name of the SQL table column.', example='Column_Name'
    )
    type: DataType = Field(
        ...,
        description='JSON object in TableSchema format; describes the data returned by the results serving API.',
        example={'type': 'CHAR', 'nullable': True, 'length': 8},
    )


class DataType(BaseModel):
    type: str = Field(..., description='The data type of the column.')
    nullable: bool = Field(
        ..., description='Indicates whether values in this column can be null.'
    )
    length: Optional[int] = Field(None, description='The length of the data type.')
    precision: Optional[int] = Field(
        None, description='The precision of the data type.'
    )
    scale: Optional[int] = Field(None, description='The scale of the data type.')
    key_type: Optional[DataType] = Field(
        None, description='The type of the key in the data type (if applicable).'
    )
    value_type: Optional[DataType] = Field(
        None, description='The type of the value in the data type (if applicable).'
    )
    element_type: Optional[DataType] = Field(
        None, description='The type of the element in the data type (if applicable).'
    )
    fields: Optional[List[RowFieldType]] = Field(
        None, description='The fields of the element in the data type (if applicable).'
    )
    resolution: Optional[str] = Field(
        None, description='The resolution of the data type (if applicable).'
    )
    fractional_precision: Optional[int] = Field(
        None, description='The fractional precision of the data type (if applicable).'
    )
    class_name: Optional[str] = Field(
        None, description='The class name of the structured data type (if applicable).'
    )


class RowFieldType(BaseModel):
    name: str = Field(..., description='The name of the field.')
    field_type: DataType = Field(..., description='The data type of the field.')
    description: Optional[str] = Field(
        None, description='The description of the field.'
    )


ColumnDetails.update_forward_refs()
DataType.update_forward_refs()
