# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    pass
