# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, constr

from .. import EnvScopedObjectReference
from ..ListMeta import ListMeta


class ApiVersion(Enum):
    usm_v1 = 'usm/v1'


class Kind(Enum):
    KafkaCluster = 'KafkaCluster'


class KafkaCluster(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    display_name: Optional[str] = Field(
        None,
        description='A human-readable name for the Confluent Platform Kafka cluster.',
        example='My-Prod-CP-Cluster',
    )
    confluent_platform_kafka_cluster_id: Optional[str] = Field(
        None,
        description='The unique identifier of the Kafka cluster within the Confluent Platform environment.',
        example='4k0R9d1GTS5tI9f4Y2xZ0Q',
    )
    cloud: Optional[str] = Field(
        None,
        description='The cloud service provider where the metadata for the Kafka Cluster should be stored.',
        example='AWS',
    )
    region: Optional[str] = Field(
        None,
        description='The home region of the Confluent Platform Kafka cluster where the metadata should be stored.',
        example='us-east-1',
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model(Enum):
    ConnectCluster = 'ConnectCluster'


class ConnectCluster(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    confluent_platform_connect_cluster_id: Optional[str] = Field(
        None,
        description='The unique identifier of the Connect cluster within the Confluent Platform environment.',
        example='connect-group-xyz123',
    )
    kafka_cluster_id: Optional[str] = Field(
        None,
        description='The unique identifier of the metadata Kafka cluster for the Connect Cluster.\n',
        example='4k0R9d1GTS5tI9f4Y2xZ0Q',
    )
    cloud: Optional[str] = Field(
        None,
        description="The cloud service provider where the metadata for the Connect Cluster should be stored.\nThis field is optional. If provided, 'region' must also be provided.\nIf neither 'cloud' nor 'region' are provided, the cloud provider of the associated\nmetadata Kafka cluster (identified by 'kafka_cluster_id') will be used as a fallback.\n",
        example='AWS',
    )
    region: Optional[str] = Field(
        None,
        description="The home region of the Confluent Platform Connect cluster where the metadata should be stored.\nThis field is optional. If provided, 'cloud' must also be provided.\nIf neither 'cloud' nor 'region' are provided, the home region of the associated\nmetadata Kafka cluster (identified by 'kafka_cluster_id') will be used as a fallback.\n",
        example='us-east-1',
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model1(Enum):
    KafkaClusterList = 'KafkaClusterList'


class Metadata(ListMeta):
    first: Optional[Any] = Field(
        None, example='https://api.confluent.cloud/usm/v1/kafka-clusters'
    )
    last: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/kafka-clusters?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/kafka-clusters?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/kafka-clusters?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class KafkaClusterList(BaseModel):
    api_version: ApiVersion = Field(
        ...,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Kind1Model1 = Field(
        ..., description='Kind defines the object this REST resource represents.'
    )
    metadata: Metadata
    data: List[KafkaCluster] = Field(
        ...,
        description='A data property that contains an array of resource items. Each entry in the array is a separate resource.',
        unique_items=True,
    )


class Kind1Model2(Enum):
    ConnectClusterList = 'ConnectClusterList'


class Metadata1Model(ListMeta):
    first: Optional[Any] = Field(
        None, example='https://api.confluent.cloud/usm/v1/connect-clusters'
    )
    last: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/connect-clusters?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/connect-clusters?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/usm/v1/connect-clusters?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class ConnectClusterList(BaseModel):
    api_version: ApiVersion = Field(
        ...,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Kind1Model2 = Field(
        ..., description='Kind defines the object this REST resource represents.'
    )
    metadata: Metadata1Model
    data: List[ConnectCluster] = Field(
        ...,
        description='A data property that contains an array of resource items. Each entry in the array is a separate resource.',
        unique_items=True,
    )
