from enum import Enum


class ToolName(str, Enum):
    """Enum of available tool names"""
    LIST_TOPICS = "list-topics"
    CREATE_TOPICS = "create-topics"
    DELETE_TOPICS = "delete-topics"
    PRODUCE_MESSAGE = "produce-message"
    CONSUME_MESSAGES = "consume-messages"
    LIST_FLINK_STATEMENTS = "list-flink-statements"
    CREATE_FLINK_STATEMENT = "create-flink-statement"
    READ_FLINK_STATEMENT = "read-flink-statement"
    DELETE_FLINK_STATEMENTS = "delete-flink-statements"
    LIST_CONNECTORS = "list-connectors"
    READ_CONNECTOR = "read-connector"
    CREATE_CONNECTOR = "create-connector"
    DELETE_CONNECTOR = "delete-connector"
    SEARCH_TOPICS_BY_TAG = "search-topics-by-tag"
    SEARCH_TOPICS_BY_NAME = "search-topics-by-name"
    CREATE_TOPIC_TAGS = "create-topic-tags"
    DELETE_TAG = "delete-tag"
    REMOVE_TAG_FROM_ENTITY = "remove-tag-from-entity"
    ADD_TAGS_TO_TOPIC = "add-tags-to-topic"
    LIST_TAGS = "list-tags"
    ALTER_TOPIC_CONFIG = "alter-topic-config"
    LIST_CLUSTERS = "list-clusters"
    LIST_ENVIRONMENTS = "list-environments"
    READ_ENVIRONMENT = "read-environment"
    LIST_SCHEMAS = "list-schemas"
    GET_TOPIC_CONFIG = "get-topic-config"
    CREATE_TABLEFLOW_TOPIC = "create-tableflow-topic"
    LIST_TABLEFLOW_REGIONS = "list-tableflow-regions"
    LIST_TABLEFLOW_TOPICS = "list-tableflow-topics"
    READ_TABLEFLOW_TOPIC = "read-tableflow-topic"
    UPDATE_TABLEFLOW_TOPIC = "update-tableflow-topic"
    DELETE_TABLEFLOW_TOPIC = "delete-tableflow-topic"
    CREATE_TABLEFLOW_CATALOG_INTEGRATION = "create-tableflow-catalog-integration"
    LIST_TABLEFLOW_CATALOG_INTEGRATIONS = "list-tableflow-catalog-integrations"
    READ_TABLEFLOW_CATALOG_INTEGRATION = "read-tableflow-catalog-integration"
    UPDATE_TABLEFLOW_CATALOG_INTEGRATION = "update-tableflow-catalog-integration"
    DELETE_TABLEFLOW_CATALOG_INTEGRATION = "delete-tableflow-catalog-integration"