# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Literal, Optional, Union
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field, constr

from .. import GlobalObjectReference, ObjectReference
from ..ListMeta import ListMeta
from ..ObjectMeta import ObjectMeta


class ApiVersion(Enum):
    pim_v2 = 'pim/v2'


class Kind(Enum):
    Integration = 'Integration'


class Usage(BaseModel):
    __root__: AnyUrl = Field(
        ...,
        description='crn that specifies the resource using this integration',
        example='crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-456xy/cloud-cluster=lkc-123abc/connector=my_datagen_connector',
    )


class GcpIntegrationConfig(BaseModel):
    google_service_account: Optional[str] = Field(
        None,
        description='The ID of the Google Service Account that Confluent Cloud uses to impersonate\ncustomer Google Service Account when it accesses resources in your GCP project.\n',
        example='cspi-sa1@cflt-project.iam.gserviceaccount.com',
    )
    customer_google_service_account: Optional[str] = Field(
        None,
        description='The ID of the Google Service Account that Confluent Cloud impersonates\nto access resources in your GCP Project.\n',
        example='customer-sa@customer-project.iam.gserviceaccount.com',
    )
    kind: Literal['GcpIntegrationConfig'] = Field(
        ...,
        description='Cloud provider specific config to which access is provided through provider integration.',
        example='GcpIntegrationConfig',
    )


class AzureIntegrationConfig(BaseModel):
    confluent_multi_tenant_app_id: Optional[str] = Field(
        None,
        description='The ID of the Confluent Multi-Tenant App that Confluent Cloud uses to impersonate\ncustomer Azure App when it accesses resources in your Azure subscription.\n',
        example='9bb441c4-edef-46ac-8a41-c49e44a3fd9a',
    )
    customer_azure_tenant_id: Optional[str] = Field(
        None,
        description="The ID of the customer's Azure Active Directory (Azure AD) tenant\n",
        example='12345678-1234-1234-1234-123456789abc',
    )
    kind: Literal['AzureIntegrationConfig'] = Field(
        ...,
        description='Cloud provider specific config to which access is provided through provider integration.',
        example='AzureIntegrationConfig',
    )


class AwsIntegrationConfig(BaseModel):
    iam_role_arn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None,
        description='Amazon Resource Name (ARN) that identifies the Amazon Web Services (AWS)\nIdentity and Access Management (IAM) role that Confluent Cloud uses to assume\ncustomer IAM role when it accesses resources in your AWS account.\n',
        example='arn:aws:iam::000000000000:role/my-test-aws-role',
    )
    external_id: Optional[UUID] = Field(
        None,
        description='Unique external ID that Confluent Cloud uses when it assumes the IAM role\nin your Amazon Web Services (AWS) account.\n',
    )
    customer_iam_role_arn: Optional[constr(min_length=20, max_length=2048)] = Field(
        None,
        description='Amazon Resource Name (ARN) that identifies the Amazon Web Services (AWS)\nIdentity and Access Management (IAM) role that Confluent Cloud assumes when\nit accesses resources in your AWS account.\n',
        example='arn:aws:iam::000000000000:role/my-test-aws-role',
    )
    kind: Literal['AwsIntegrationConfig'] = Field(
        ...,
        description='Cloud provider specific config to which access is provided through provider integration.',
        example='AwsIntegrationConfig',
    )


class Kind1Model(Enum):
    IntegrationValidateRequest = 'IntegrationValidateRequest'


class Metadata(ObjectMeta):
    self: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/pim/v2/integration-validate-requests/ivr-12345',
    )
    resource_name: Optional[Any] = Field(
        None,
        example='crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/integration-validate-request=ivr-12345',
    )


class IntegrationValidateRequest(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='The ID of the provider integration to validate.',
        example='cspi-00000',
    )
    metadata: Optional[Metadata] = None
    config: Optional[
        Union[GcpIntegrationConfig, AzureIntegrationConfig, AwsIntegrationConfig]
    ] = Field(
        None,
        description='Cloud provider specific configuration for the provider integration.\nRequired only for integrations in `DRAFT` status.\n',
        discriminator='kind',
    )
    environment: Optional[GlobalObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model1(Enum):
    IntegrationList = 'IntegrationList'


class Metadata1Model(ListMeta):
    first: Optional[Any] = Field(
        None, example='https://api.confluent.cloud/pim/v2/integrations'
    )
    last: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/pim/v2/integrations?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/pim/v2/integrations?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/pim/v2/integrations?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class Kind1Model2(Enum):
    Integration = 'Integration'


class IntegrationUpdate(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model2] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    config: Optional[
        Union[GcpIntegrationConfig, AzureIntegrationConfig, AwsIntegrationConfig]
    ] = Field(
        None,
        description='Cloud provider specific configuration for the provider integration.\nRequired only when updating integrations with `DRAFT` status. Not required during creation.\n',
        discriminator='kind',
    )
    usages: Optional[List[Usage]] = Field(
        None,
        description='List of resource crns where this integration is being used.',
        min_items=0,
    )
    status: Optional[str] = Field(
        None,
        description='Status of the provider integration.\n- `DRAFT`: Integration exists but is not associated with customer configuration\n- `CREATED`: Integration has been associated with customer configuration\n- `ACTIVE`: Integration is in use by Confluent resources\n',
        example='CREATED',
    )
    environment: Optional[ObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Integration(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    display_name: Optional[constr(max_length=60)] = Field(
        None,
        description='Display name of Provider Integration.',
        example='bigquery_provider_integration',
    )
    provider: Optional[str] = Field(
        'GCP',
        description='Cloud provider to which access is provided through provider integration.',
        example='GCP',
    )
    config: Optional[
        Union[GcpIntegrationConfig, AzureIntegrationConfig, AwsIntegrationConfig]
    ] = Field(
        None,
        description='Cloud provider specific configuration for the provider integration.\nRequired only when updating integrations with `DRAFT` status. Not required during creation.\n',
        discriminator='kind',
    )
    usages: Optional[List[Usage]] = Field(
        None,
        description='List of resource crns where this integration is being used.',
        min_items=0,
    )
    status: Optional[str] = Field(
        None,
        description='Status of the provider integration.\n- `DRAFT`: Integration exists but is not associated with customer configuration\n- `CREATED`: Integration has been associated with customer configuration\n- `ACTIVE`: Integration is in use by Confluent resources\n',
        example='CREATED',
    )
    environment: Optional[ObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class IntegrationList(BaseModel):
    api_version: ApiVersion = Field(
        ...,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Kind1Model1 = Field(
        ..., description='Kind defines the object this REST resource represents.'
    )
    metadata: Metadata1Model
    data: List[Integration] = Field(
        ...,
        description='A data property that contains an array of resource items. Each entry in the array is a separate resource.',
        unique_items=True,
    )
