# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class PresignedUrl(BaseModel):
    location: Literal['PRESIGNED_URL_LOCATION'] = Field(
        ...,
        description='Location of the Custom Connector Plugin source.\n',
        example='PRESIGNED_URL_LOCATION',
    )
    upload_id: str = Field(
        ...,
        description='Upload ID returned by the `/presigned-upload-url` API. This field returns an empty string in all responses.',
        example='e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66',
    )
