# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-11-13T03:02:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr

from ... import EnvScopedObjectReference
from ...ListMeta import ListMeta
from ...ObjectMeta import ObjectMeta
from .. import UploadSource


class ApiVersion(Enum):
    ccpm_v1 = 'ccpm/v1'


class Kind(Enum):
    CustomConnectPlugin = 'CustomConnectPlugin'


class Metadata(ObjectMeta):
    self: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345?environment=env-abc123',
    )
    resource_name: Optional[Any] = Field(
        None,
        example='crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/custom-connect-plugin=ccp-12345',
    )


class Kind1Model(Enum):
    PresignedUrl = 'PresignedUrl'


class PresignedUrl(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    content_format: Optional[str] = Field(
        None,
        description='Content format of the Custom Connect Plugin archive.',
        example='ZIP',
    )
    cloud: Optional[str] = Field(
        None,
        description='Cloud provider where the Custom Connect Plugin archive is uploaded.',
        example='AWS',
    )
    upload_id: Optional[str] = Field(
        None,
        description='Unique identifier of this upload.',
        example='e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66',
    )
    upload_url: Optional[AnyUrl] = Field(
        None,
        description='Upload URL for the Custom Connect Plugin archive.',
        example='https://confluent-custom-connectors-stag-us-west-2.s3.dualstack.us-west-2.amazonaws.com/',
    )
    upload_form_data: Optional[Dict[str, Any]] = Field(
        None,
        description='Upload form data of the Custom Connect Plugin. All values should be strings.',
        example={
            'bucket': 'confluent-custom-connectors-stag-us-west-2',
            'key': 'staging/custom-plugin/2f37f0b6-f8da-4e8b-bc5f-282ebb0511be/connect-e53bb2e8-8de3-49fa-9fb1-4e3fd9a16b66/plugin.zip',
            'policy': 'string',
            'x-amz-algorithm': 'AWS4-HMAC-SHA256',
            'x-amz-credential': 'string',
            'x-amz-date': '20230725T013857Z',
            'x-amz-security-token': 'string',
            'x-amz-signature': 'string',
        },
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model1(Enum):
    CustomConnectPluginVersion = 'CustomConnectPluginVersion'


class Metadata1Model(ObjectMeta):
    self: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345/versions/ver-12345?environment=env-abc123',
    )
    resource_name: Optional[Any] = Field(
        None,
        example='crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/custom-connect-plugin=ccp-12345/version=ver-12345',
    )


class CustomConnectPluginVersionStatus(BaseModel):
    phase: constr(max_length=50) = Field(
        ...,
        description='Phase of the Custom Connect Plugin Version.',
        example='PROCESSING',
    )
    error_message: Optional[constr(max_length=256)] = Field(
        None,
        description='Displayable error message if version is in a failed state',
        example='Version creation failed due to invalid plugin archive.',
    )


class ConnectorClass(BaseModel):
    class_name: constr(
        regex=r'^(([a-zA-Z][a-zA-Z_$0-9]*(\.[a-zA-Z][a-zA-Z_$0-9]*)*)\.)?([a-zA-Z][a-zA-Z_$0-9]*)$',
        max_length=150,
    ) = Field(
        ...,
        description='Java class or alias for connector. You can get connector class from connector documentation provided by developer.',
        example='io.confluent.kafka.connect.datagen.DatagenConnector',
    )
    type: str = Field(
        ...,
        description='Type of the connector class. Should be either `SOURCE` or `SINK`.\n',
        example='SOURCE',
    )


class Kind1Model2(Enum):
    CustomConnectPluginList = 'CustomConnectPluginList'


class Metadata1Model1(ListMeta):
    first: Optional[Any] = Field(
        None, example='https://api.confluent.cloud/ccpm/v1/plugins'
    )
    last: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class CustomConnectPluginSpec(BaseModel):
    cloud: Optional[str] = Field(
        None,
        description='Cloud provider where the Custom Connect Plugin archive is uploaded.',
        example='AWS',
    )
    display_name: Optional[constr(max_length=60)] = Field(
        None, description='Display name of Custom Connect Plugin.'
    )
    description: Optional[constr(max_length=256)] = Field(
        None, description='Description of Custom Connect Plugin.'
    )
    runtime_language: Optional[str] = Field(
        None, description='Runtime language of Custom Connect Plugin.', example='JAVA'
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model3(Enum):
    CustomConnectPluginVersionList = 'CustomConnectPluginVersionList'


class Metadata1Model2(ListMeta):
    first: Optional[Any] = Field(
        None, example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345/versions'
    )
    last: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345/versions?page_token=bcAOehAY8F16YD84Z1wT',
    )
    prev: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345/versions?page_token=YIXRY97wWYmwzrax4dld',
    )
    next: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345/versions?page_token=UvmDWOB1iwfAIBPj6EYb',
    )


class CustomConnectPluginVersionSpec(BaseModel):
    version: Optional[constr(max_length=60)] = Field(
        None,
        description='Version of the Custom Connect Plugin.\nThe version must comply with SemVer (e.g., `1.2.3`, `1.2.3-beta`, `1.2.3-rc.123`, `1.2.3-rc.123+build.456`).\n',
    )
    sensitive_config_properties: Optional[
        List[constr(regex=r'^[\w\+\.-]+$', max_length=150)]
    ] = Field(
        None,
        description='A sensitive property is a connector configuration property that must be hidden after a user enters property\nvalue when setting up connector.\n',
        example=['passwords', 'keys', 'tokens'],
    )
    documentation_link: Optional[
        constr(regex=r'^$|^(http://|https://).+', max_length=512)
    ] = Field(
        None,
        description='Document link of Custom Connect Plugin.',
        example='https://github.com/confluentinc/kafka-connect-datagen',
    )
    content_format: Optional[str] = Field(
        None, description='Archive format of Custom Connect Plugin.', example='ZIP'
    )
    connector_classes: Optional[List[ConnectorClass]] = Field(
        None,
        description='List of connector classes.\nThe connector class must be a valid Java class name or alias for the connector.\nYou can get the connector class from the connector documentation provided by the developer.\n',
        max_items=10,
        min_items=1,
    )
    upload_source: Optional[UploadSource.PresignedUrl] = Field(
        None,
        description='Upload source of Custom Connect Plugin Version. Only required in `create` request,\nwill be ignored in `read`, `update` or `list`.\n',
        discriminator='location',
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class CustomConnectPluginSpecUpdate(BaseModel):
    display_name: Optional[constr(max_length=60)] = Field(
        None, description='Display name of Custom Connect Plugin.'
    )
    description: Optional[constr(max_length=256)] = Field(
        None, description='Description of Custom Connect Plugin.'
    )
    runtime_language: Optional[str] = Field(
        None, description='Runtime language of Custom Connect Plugin.', example='JAVA'
    )
    environment: Optional[EnvScopedObjectReference] = Field(
        None, description='The environment to which this belongs.'
    )


class Kind1Model4(Enum):
    CustomConnectPlugin = 'CustomConnectPlugin'


class Metadata1Model3(ObjectMeta):
    self: Optional[Any] = Field(
        None,
        example='https://api.confluent.cloud/ccpm/v1/plugins/ccp-12345?environment=env-abc123',
    )
    resource_name: Optional[Any] = Field(
        None,
        example='crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-abc123/custom-connect-plugin=ccp-12345',
    )


class CustomConnectPluginUpdate(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model4] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    metadata: Optional[Metadata1Model3] = None
    spec: Optional[CustomConnectPluginSpecUpdate] = None


class CustomConnectPlugin(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    metadata: Optional[Metadata] = None
    spec: Optional[CustomConnectPluginSpec] = None


class CustomConnectPluginVersion(BaseModel):
    api_version: Optional[ApiVersion] = Field(
        None,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Optional[Kind1Model1] = Field(
        None, description='Kind defines the object this REST resource represents.'
    )
    id: Optional[constr(max_length=255)] = Field(
        None,
        description='ID is the "natural identifier" for an object within its scope/namespace; it is normally unique across time but not space. That is, you can assume that the ID will not be reclaimed and reused after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or objects of the same `kind` within a different scope/namespace ("space").',
        example='dlz-f3a90de',
    )
    metadata: Optional[Metadata1Model] = None
    spec: Optional[CustomConnectPluginVersionSpec] = None
    status: Optional[CustomConnectPluginVersionStatus] = None


class Datum(CustomConnectPlugin):
    spec: Dict[str, Any]


class CustomConnectPluginList(BaseModel):
    api_version: ApiVersion = Field(
        ...,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Kind1Model2 = Field(
        ..., description='Kind defines the object this REST resource represents.'
    )
    metadata: Metadata1Model1
    data: List[Datum] = Field(
        ...,
        description='A data property that contains an array of resource items. Each entry in the array is a separate resource.',
        unique_items=True,
    )


class Datum1Model(CustomConnectPluginVersion):
    spec: Dict[str, Any]


class CustomConnectPluginVersionList(BaseModel):
    api_version: ApiVersion = Field(
        ...,
        description='APIVersion defines the schema version of this representation of a resource.',
    )
    kind: Kind1Model3 = Field(
        ..., description='Kind defines the object this REST resource represents.'
    )
    metadata: Metadata1Model2
    data: List[Datum1Model] = Field(
        ...,
        description='A data property that contains an array of resource items. Each entry in the array is a separate resource.',
        unique_items=True,
    )
